cmake -S . -B build_release -G "Visual Studio 17 2022" -D3RD_PATH=C:\Users\Bluesky\Desktop\SKY\Sky3RD_output -DSKY_BUILD_EDITOR=ON -DSKY_BUILD_TEST=ON -DSKY_BUILD_BULLET=ON -DSKY_BUILD_FREETYPE=ON -DSKY_BUILD_TERRAIN=ON -DSKY_BUILD_COMPRESSION=ON -DSKY_BUILD_TOOL=ON -DSKY_USE_TRACY=OFF -DCMAKE_INSTALL_PREFIX=build/install

pause